name: Nix Flake

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "master"
    paths:
      - "**.nix"
      - "flake.lock"
      - "Cargo.toml"
      - "Cargo.lock"
      - "crates/**"
      - ".github/workflows/nix.yml"
  pull_request:
    paths:
      - "**.nix"
      - "flake.lock"
      - "Cargo.toml"
      - "Cargo.lock"
      - "crates/**"
      - ".github/workflows/nix.yml"
  workflow_dispatch:

jobs:
  check-flake:
    name: Validate Flake & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@84c0677f58dcedf3b91f8223ce36a9ea5b3c84b7 # v15

      - name: Check flake formatting and evaluation
        run: nix flake check

      - name: Build default package
        run: nix build .#default
